### ISSUE TITLE
Support serializing maps and nested structs

### ISSUE THREAD

**Issue by rnag** [nox/serde_urlencoded#103]
Hi all, I looked a little bit into the docs so I'm not sure if this behavior is currently supported, please correct me if so.

Basically what I'm looking to do is serialize a nested `struct` into a query string, i.e. where the value is like `json` data essentially.

In my particular use case, here are the API docs which I'm currently referencing:
https://support.monday.com/hc/en-us/articles/4406042650002-Audit-Log-API

As you can see from the docs, the query param fields like `start_time` and `end_time` would need to be json encoded into the query string, so for a specific example they had:

```plaintext
?page=1&per_page=20&filters={"start_time":"2021-08-24T17:03:00Z"}
```

To achieve this, I tried to use a nested struct which was defined as below:

```rust
/// Get Audit Logs API - max. results per page (default)
const MAX_PER_PAGE: u16 = 1000;

/// Query Parameters to be used in the request for the *Audit Log API*.
#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogParams<'a> {
    pub page: u16,
    pub per_page: u16,
    #[serde(borrow)]
    // Optional
    pub filters: Option<FilterParams<'a>>,
}

#[derive(Default, Debug, Serialize, Deserialize)]
pub struct FilterParams<'a> {
    #[serde(skip_serializing_if = "str::is_empty")]
    pub start_time: &'a str,
    #[serde(skip_serializing_if = "str::is_empty")]
    pub end_time: &'a str,
}

impl<'a> Default for AuditLogParams<'a> {
    fn default() -> Self {
        Self {
            page: 1,
            per_page: MAX_PER_PAGE,
            filters: None,
        }
    }
}

impl<'a> From<FilterParams<'a>> for AuditLogParams<'a> {
    fn from(filters: FilterParams<'a>) -> Self {
        Self {
            filters: Some(filters),
            ..Default::default()
        }
    }
}
```

However, when I serialize a nested struct data with the `filters` field correctly populated, and using below syntax with the `reqwest` library:

```rust
let filters = FilterParams {
    start_time: "2021-08-24T17:03:00Z",
    ..Default::default()
};
let params = AuditLogParams::from(filters);

let r = self.client.get(GET_LOGS_URL).query(&params).send().await?;
```

I am receiving an `builder error: unsupported value` error at runtime, from the console logs at least. So I was curious if there was a best practice or recommended approach to building a query parameters string in the above format.

**Comment by rnag** [comment]
*Update*: It looks like currently `serde_url_encoded` might not support nested `struct` or also `HashMap` (and other map-like) types. If anyone is curious, my current workaround is to implement a custom `Serializer` for the main struct, defined as follows:

```rust
impl<'a> Serialize for AuditLogParams<'a> {
    fn serialize<S>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut s = serializer.serialize_struct("Person", 3)?;
        s.serialize_field("page", &self.page)?;
        s.serialize_field("per_page", &self.per_page)?;
        if let Some(ref filters) = self.filters {
            s.serialize_field("filters", &serde_json::to_string(filters).unwrap())?;
        }
        s.end()
    }
}
```

Then my tests in the crate now look like this:

```rust
#[cfg(test)]
mod tests {
    use super::*;
    use serde_urlencoded::to_string;

    #[test]
    fn test_serialize_filters_as_url_encoded_params() -> Result<()> {
        sensible_env_logger::safe_init!();

        let filters = Some(FilterParams {
            start_time: "2020-08-24T17:03:00Z",
            end_time: "",
        });

        let params = AuditLogParams {
            filters,
            ..Default::default()
        };

        let result = to_string(params)?;
        trace!(result);

        // result contains `start_time` but *not* the `end_time`
        assert!(result.contains("start_time"));
        assert!(!result.contains("end_time"));

        Ok(())
    }
```

**Comment by rnag** [comment]
Hi @nox , curious if any update was implemented as part of this issue? I did put together a workaround which appears to work for now, however I think it would be great if `serde_urlencoded` supported this use case (nested structs and maps) out of the box. I think it would be pretty unambiguous to implement as well - essentially just using `serde_json` library to serialize the nested values.

**Comment by nox** [comment]
The solution is to just use serde_json yourself for whichever keys you want
