### ISSUE TITLE
Support serializing bytes

### ISSUE THREAD

**Issue by bk2204** [nox/serde_urlencoded#104]
Right now, byte-like things (e.g., `&[u8]`) are only serialized if they can be converted to strings.  However, there's no such limitation in the actual encoding and arbitrary byte sequences can be encoded in `application/x-www-form-urlencoded` by simply encoding the bytes with percent-encoding if necessary.

As a practical matter, this prevents sending such values in Reqwest's query parameters, which I'm trying to do right now.

**Comment by nox** [comment]
`application/x-www-form-urlencoded` only deals with UTF-8 strings.

https://url.spec.whatwg.org/#application/x-www-form-urlencoded
