### ISSUE TITLE
New type structs support

### ISSUE THREAD

**Issue by miedzinski** [nox/serde_urlencoded#14]
New type structs don't seem to work as intended.

```rust
#[derive(Debug, Deserialize, Serialize)]
pub struct RequestToken(String);

#[derive(Deserialize)]
pub struct OauthRequest {
    #[serde(rename = "code")]
    pub request_token: RequestToken,
}
```

Given `some_data` has `code=1d96c242-0e47-212b-a80e-560216`

```
let request: OauthRequest = serde_urlencoded::from_reader(some_data)?;
```

fails with `Error { err: "invalid type: string \"1d96c242-0e47-212b-a80e-560216\", expected tuple struct RequestToken" }`.

I'm using serde 0.9.7, serde_derive 0.9.7, serde_urlencoded 0.4.2 on Rust 1.15.1.

**Comment by nox** [comment]
Thanks for the report!

> 18:43 &lt;dtolnay> looks like all of the Deserializer implementations in this file are missing deserialize_newtype_struct https://docs.serde.rs/src/serde/de/value.rs.html

**Comment by nox** [comment]
This was fixed upstream AFAIK.
