### ISSUE TITLE
Any interest in supporting complex structs via Ruby/Rails-style nested params?

### ISSUE THREAD

**Issue by samscott89** [nox/serde_urlencoded#15]
Hi,

I was playing around with adding support of nested structs. I hacked together a basic implementation building off the existing code which supports structs like this:
```rust
struct Foo { bar: Bar, baz: Baz }
struct Bar { x: u8, y: String }
struct Baz { thing: String, other: u8 }

let foo = Foo {
  bar: Bar { x: 10, y: "Ten".to_owned()  },
  baz: Baz { thing: "Thing".to_owned(), other: 12  }
};
```

Then 
```rust
serde_urlencoded::to_string(&foo)
```
Outputs:
```text
bar[x]=10&bar[y]=Ten&baz[thing]=Thing&baz[other]=12
```
(although with brackets urlencoded as `%5B`, `%5D`).

And similarly, that string (with or without using `%5B`/`%5D` serializes back to the expected struct.

Is this something which people want to see added to this crate? If so, I can clean up the code and submit a PR. Probably would be hidden behind a feature flag, since it is almost certainly going to be slower than the existing method and not formally supported.

**Comment by samscott89** [comment]
Oh, and to reproduce this behaviour in Ruby:
```ruby
require 'rack'
Rack::Utils::parse_nested_query "bar[x]=10&bar[y]=Ten&baz[thing]=Thing&baz[other]=12"
# => {"bar"=>{"x"=>"10", "y"=>"Ten"}, "baz"=>{"thing"=>"Thing", "other"=>"12"}} 
```

**Comment by nox** [comment]
See #6.

**Comment by samscott89** [comment]
Yeah, I was thinking that these changes would naturally encompass that feature as well.

**Comment by samscott89** [comment]
Sorry, but I don't really understand your previous comment. You said previously you were going to write a related feature, am I to take this as meaning you are open to a PR for this or that you are already working on it?

**Comment by kestred** [comment]
I would also like to see this type of serialization supported

**Comment by samscott89** [comment]
Hey all, I've created [serde_qs](https://github.com/samscott89/serde_qs) to fill this gap, since I think the extra functionality needed would be unnecessarily cumbersome to this library. So I'm closing this issue.
