### ISSUE TITLE
Cannot serialize a simple two element tuple

### ISSUE THREAD

**Issue by sbstp** [nox/serde_urlencoded#28]
I'm currently working on a little [addition](https://github.com/seanmonstar/reqwest/issues/239) to `reqwest` and I've noticed this issue. For our usage case, it's possible to only want to serialize a simple tuple composed of a key and a value. I used the target provided the `url` crate, via `url::query_pairs_mut` for the serializer's target.
```rust
extern crate serde_urlencoded;

use serde_urlencoded::to_string;

fn main() {
    println!("{:?}", to_string(("foo", "qux"))); // unsupported pair
    println!("{:?}", to_string(&("foo", "qux"))); // unsupported pair
    println!("{:?}", to_string([("foo", "qux")])); // ok
}
```
Output:
```
Err(Custom("unsupported pair"))
Err(Custom("unsupported pair"))
Ok("foo=qux")
```

**Comment by nox** [comment]
Thanks for the report but I will not support this. First because I don’t think it makes sense to support both sequences of things and a single thing itself, and furthermore because tuples and fixed size arrays go through the same code path in the serde data model, which would make ˋ&[(K, V)]ˋ weirder to support.

**Comment by sbstp** [comment]
I tried tracing the first two examples, and for some reason they don't go through `serialize_tuple` or `serialize_seq`, which seems pretty weird. It's as if the tuple was ignored. But the [source code](https://docs.rs/serde/1.0.27/src/serde/ser/impls.rs.html#253-268) seems to call `serialize_tuple`, so I'm not sure what's going on. Do you know what's going on with this?

I understand that it might not make sense generally, but for our use case it actually makes sense to support both sequences of key-vals and simple key-vals. The `UrlQuery` target appends/overwrites. [Here](https://github.com/sbstp/reqwest/commit/b72b209fb8111eda245e691aec952dddab096af6#diff-2873e3b87f87572c686867a1c112e3fdR560)'s an example of it being called multiple times without any issues.

**Comment by nox** [comment]
I understand that, but this doesn't mean the serialiser should support passing `(K, V)`, given it would make `[(K, V); N]` more difficult to support. Fixed-size arrays and tuples go through the same machinery in Serde.

**Comment by ivarflakstad** [comment]
Hey!
I'm obviously super late to the party - but just wanted to check if this could be solved by adding a trait restriction that prevents users from passing in plain `(K, V)` etc?
