### ISSUE TITLE
Expose non top-level serialization

### ISSUE THREAD

**Issue by WiSaGaN** [nox/serde_urlencoded#29]
Currently `serde_urlencoded` only supports top-level serialization. An attempt to serialize a new type wrapping a float will fail with "top-level serializer supports only maps and structs".

In some argument signing cases, we want to know the exact serialization result for a particular field `serde_urlencoded` has done. Maybe we can have some util to expose these serializers?

**Comment by nox** [comment]
Please show an example, because I'm not sure what you mean. At the very least "a new type wrapping a float" doesn't sound like a type that represents a collection of key-value pairs, why should that be supported by this crate?

**Comment by WiSaGaN** [comment]
Say, we have a struct
```
struct Foo {
    pub bar1: Bar1,
    pub bar2: Bar2,
}
```
which represents arguments I want to send as a HTTP POST. Meanwhile I need to sign the arguments by applying a `MD5` over a string of `bar1=xxx&bar2=yyy&somekey`, in which case I need to know what exact "xxx" and "yyy" are when encoded from the value of `bar1` and `bar2`. It would be good to have some `part::to_string(&foo.bar1)` to be "xxx".

**Comment by nox** [comment]
This use case is already supported, so please give more details.

**Comment by nox** [comment]
I mean, you can just get the `md5` fingerprint of the whole string. Why would you want each field separately?

**Comment by nox** [comment]
You can use [`byte_serialize`](https://docs.rs/url/1.6.0/url/form_urlencoded/fn.byte_serialize.html) from the url crate to encode whatever you want separately. I'm closing this issue.
