### ISSUE TITLE
Support Option type

### ISSUE THREAD

**Issue by mre** [nox/serde_urlencoded#3]
Hi,

thanks for this crate. It's very helpful already. :smiley: 
One thing I need the most right now are `Option` types.

Here's some test code:

```rust
#![feature(plugin, custom_derive)]
#![plugin(serde_macros)]

extern crate serde;
extern crate serde_urlencoded;

#[derive(Debug, Serialize, Deserialize)]
struct Parameters {
    channel: String,
    last: Option<f64>,
    ts: i64,
}

fn main() {
    
    let params = Parameters {
        channel: "mychannel".to_string(),
        last: Some(1.234),
        ts: 23,
    };
    println!("{:?}", serde_urlencoded::to_string(&params));
}

```

I've seen that the implementation should be at [this position](https://github.com/nox/serde_urlencoded/blob/448749d0186368f93d937efa8034718baf87a9d5/src/ser/value.rs#L167) and I would like to offer my help.

What I would do is match on `Option` and if it's `Some(value)` I would `self.append_pair(value)`.
On the other hand I'm not sure what I would do in case of `None`. Maybe I should simply return?

**Comment by dtolnay** [comment]
@mre `append_pair` has an argument that is `&str` while the argument to `serialize_some` is any type `T: Serialize` so it won't work to call it directly. Instead you can do this:

```rust
#[inline]
fn serialize_some<T>(&mut self, value: T) -> Result<(), Error>
    where T: ser::Serialize
{
    value.serialize(self)
}
```

That way the `T` will correctly serialize itself regardless of what type it is, as long as it is one of the ones already supported by serde_urlencoded.

And yes, I think `serialize_none` can just return without doing anything although you should confirm that it works that way.

Thanks for looking into this!

**Comment by mre** [comment]
Initial implementation in #4. Thanks for the support @dtolnay. :smiley:

**Comment by mre** [comment]
Merged. Closing this.

**Comment by nox** [comment]
I published it in `0.2.1`, thanks again for your contribution!

**Comment by mre** [comment]
You're very welcome. Thanks for the support to you and @dtolnay.

**Comment by nox** [comment]
I could have helped you faster if I had not forgotten to subscribe to my own repository, missed all the notifications for days until someone pinged me on IRC. Glad @dtolnay could help you, feel free to hang around #serde on the Mozilla IRC network!
