### ISSUE TITLE
Deserializing Option<i32> fails on empty string

### ISSUE THREAD

**Issue by joerixaop** [nox/serde_urlencoded#36]
This is not very ergonomic, because an empty string is exactly what a browser will send when an input field is left empty by the user. This means that the only way to have an optional number field is therefore to have client side Javascript to remove optional fields that stay empty.

**Comment by nox** [comment]
An empty string isn't a missing value, I don't plan to change this.

**Comment by cedeber** [comment]
Unfortunately, for the web, an empty string is an empty/optional input. Even for JS, `""` is falsy, very probably for the same reason. So instead of returning an error, it should return `None` imho, even for the `String` type, which is what an optional input field should be, don't you think? I mean, the web is what it is :-/

**Comment by imbolc** [comment]
I've just stumbled upon the same issue:
* the current solution is consistent: there's no question about the corner case of `Option<&str>` - should it be `None` or Some("")
*  but it suffers in terms of practicality. Browsers and js widgets often send `key=` for empty fields. We can't influence this.

Currently the only way I see - is to use `Option<&str>` for all optional fields and then parse types by hands :) Would adding something like `from_str_unstrictly` be a solution?

[Rocket-0.5] for example has chosen the practical side:
```rust
#[rocket::launch]
async fn rocket() -> _ {
    rocket::build().mount("/", rocket::routes![query])
}

#[rocket::get("/?<foo>&<bar>")]
async fn query(foo: Option<&str>, bar: Option<i32>) -> String {
    format!("foo={:?}, bar={:?}", foo, bar)
}
```

```sh
curl 'http://127.0.0.1:8000/?foo=&bar='
foo=Some(""), bar=None
```
They actually seem to treat all broken optional fields as non-existing:
```sh
curl 'http://127.0.0.1:8000/?bar=baz'
foo=None, bar=None
```

[Rocket-0.5]: https://github.com/SergioBenitez/Rocket/tree/v0.5-rc

**Comment by jplatte** [comment]
I agree that the current behavior makes sense. If you need the behavior requested in this issue, you can use this: https://github.com/ruma/ruma/blob/56801780b659be609bbcb9ce3701ed2676130304/crates/ruma-serde/src/strings.rs#L10-L32

**Comment by boohba** [comment]
> An empty string isn't a missing value, I don't plan to change this.
It is.

**Comment by nox** [comment]
Locking because y'all don't seem to know what "I don't plan to change this" mean.
