### ISSUE TITLE
interest in supporting nested querystrings?

### ISSUE THREAD

**Issue by hwchen** [nox/serde_urlencoded#38]
Hello!

I just started trying out [warp](https://github.com/seanmonstar/warp), which deserializes querystrings via serde_urlencoded.

I have a use case for nested querystrings, and I've been experimenting using [serde_qs](https://github.com/samscott89/serde_qs).

Is there any interest in supporting nested querystrings in serde_urlencoded, or is that beyond the scope of this project?

https://github.com/seanmonstar/warp/issues/22

**Comment by nox** [comment]
That’s indeed beyond the scope of the project.

**Comment by hwchen** [comment]
Ok, thanks!
