### ISSUE TITLE
Allow encoding spaces as %20 instead of +

### ISSUE THREAD

**Issue by kpcyrd** [nox/serde_urlencoded#39]
I ran into an issue with a parser that doesn't replace `+` with spaces, it might be a good idea to have a `to_string` function that accepts additional arguments regarding url encoding (like a config struct).

Thanks!

**Comment by nox** [comment]
`serde_urlencoded` doesn't do the encoding itself, it just delegates to `url::form_urlencoded`.

You can use `url::form_urlencoded::parse_with_encoding` and then `serde_urlencoded::Deserializer::new`.
