### ISSUE TITLE
Support serializing byte arrays

### ISSUE THREAD

**Issue by ratorx** [nox/serde_urlencoded#44]
There has been some discussion in the [servo/rust-url](https://github.com/servo/rust-url/issues/219) library about serialization of arbitrary byte arrays, but it was rejected from their main Serializer. Currently, this library doesn't support serialization of arbitrary byte arrays either due to the above choice. However, this support could be added as rust-url does supply convenience functions to serialize byte arrays.

I was wondering if support for this could be considered. My specific use case is writing a torrent client, which requires the underlying bytes of a SHA1 hash to be urlencoded as a query parameter.

**Comment by nox** [comment]
As @SimonSapin says in the issue you linked:

> In the WHATWG specification and in the rust-url implementation of `application/x-www-form-urlencoded`, the keys and values are both Unicode.

This crate also follows the WHATWG spec, so this is out of scope.

**Comment by Hexilee** [comment]
@nox  Could you please take it into consideration again? As almost all bowsers and other HTTP client support arbitrary bytes encoding, and there are so many HTTP servers receiving urlencoded-form with non-UTF8  string.
In many cases, if the html is sent in non-UTF8 encoding, and form has default value (non-UTF8), then the bowser have to encode it, and, scraper written in Rust also have to do.
If a PR is welcome, I can create one.

**Comment by Hexilee** [comment]
I really need it, If you persist in your claim, then I have to create a fork.

**Comment by nox** [comment]
> I really need it, If you persist in your claim, then I have to create a fork.

I don't appreciate your tone but you are free to fork it, not like the method you want cannot live outside of `serde_urlencoded` anyway.
