### ISSUE TITLE
Support serializing Vec values.

### ISSUE THREAD

**Issue by swalladge** [nox/serde_urlencoded#46]
I was attempting to serialize the following struct to send in query params with reqwest:

```
#[derive(Serialize, Debug)]
struct Params {
    pub urls: Vec<String>,
    pub return_id: String,
}
```

And it returned this error:

```
    ReqwestError(
        Inner {
            kind: UrlEncoded(
                Custom(
                    "unsupported value"
                )
            ),
            url: None
        }
    )
```

The use case is when an api allows a list of query params formatted like `urls[]=...&urls[]=...`. I was able to work around it by using a top level list of two-tuples instead of the struct, but support for serializing this would be nice.

**Comment by nox** [comment]
Working with sequences is explicitly out of scope for this crate. Use `serde_qs`.

**Comment by bouk** [comment]
For other people who find this issue, you can use this crate, which is a fork: https://docs.rs/serde_html_form/latest/serde_html_form/

It's also used by axum-extra's [Form extractor](https://docs.rs/axum-extra/latest/axum_extra/extract/struct.Form.html)
