### ISSUE TITLE
binary data unsupported

### ISSUE THREAD

**Issue by robinvd** [nox/serde_urlencoded#48]
binary data would be represented in rust as `Vec<u8>` or `&[u8]`, but this cannot be serialized (with error `Custom("unsupported value")`). Related to #46, but i do think this is in scope of this library as it does not include any nested values or sequences but a single binary string

example:
binary hash (displayed in hex): `7736da1861d2d31ac2abc41ccde47379c7a678d2`
in url encoding: `%77%36%da%18%61%d2%d3%1a%c2%ab%c4%1c%cd%e4%73%79%c7%a6%78%d2`

**Comment by nox** [comment]
`Vec<u8>` isn't a key-value pair so that's definitely out of scope.

**Comment by nox** [comment]
For further reference, [this](https://url.spec.whatwg.org/#application/x-www-form-urlencoded) is the only thing this crate is about.

**Comment by robinvd** [comment]
i mean, binary data for the values, currently strings are [precent encoded](https://url.spec.whatwg.org/#percent-encoded-bytes), but there is no option to do this for binary strings (&[u8] in rust).

**Comment by robinvd** [comment]
seems to be a duplicate of #44
