### ISSUE TITLE
Question: Encoding a key with no value

### ISSUE THREAD

**Issue by robojeb** [nox/serde_urlencoded#49]
I am using this via the Reqwests crate. 

I have an endpoint which requires that I encode some flags as a key only with no value. 
I can't figure out if there is a way to do this from a struct. 

```
struct Query {
    key_only: bool,
}
```

If `key_only` is true I need the Query URL to be `?key_only` but right now I can only get `key_only=true`. 

I tried using a combination of `skip_if` and unit types but unit types can't be serialized with this yet. 

Is there currently a way to do this? 
I would say this is likely related to #43

**Comment by nox** [comment]
This crate follows the serialisation algorithm from [the spec](https://url.spec.whatwg.org/#concept-urlencoded-serializer), so it doesn't support your use case and won't ever support it in the future.
