### ISSUE TITLE
Consider support of sequences

### ISSUE THREAD

**Issue by manifest** [nox/serde_urlencoded#52]
In case of our application we need to pass bounded ranges in query string of our list requests

```
?time=[1551067000, 155106800)
```
```rust
struct Qs {
  time: (Bound<DateTime<Utc>>, Bound<DateTime<Utc>),
}
```

I can also imagine situations where passing tuples and lists would be useful

```
?colors=[red, green, blue]
```
```rust
struct Qs {
  colors: Vec<String>,
}
```

```
?color=[100, 100, 100]
```
```rust
struct Qs {
  color: Color,
}
struct Color {
  red: i8,
  green: i8,
  blue: i8,
}
```

There is no RFC for such a string representation, only practical sense. Will you accept the format?

**Comment by nox** [comment]
Nope. Use `serde_qs`, or implement `Deserialize` yourself from these types by rely on `serde_json` on the value string or something like that. This is not a crate for practical sense, this is a crate for deserialising from query strings as specified by the URL Standard, nothing more, nothing less.
