### ISSUE TITLE
Deserialize &'a str

### ISSUE THREAD

**Issue by allevo** [nox/serde_urlencoded#53]
I'm trying to deserialize a struct that contains a `&'a str`:
```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_urlencoded; // 0.5.4;

#[derive(Deserialize)]
struct MyParams<'a> {
    key: &'a str
}

fn main() -> Result<(), Box<std::error::Error>> {
    println!("{:?}", "aaa");
    let r: MyParams = serde_urlencoded::from_str("key=bb").unwrap();
    println!("{:?}", r.key);
    Ok(())
}
```

But the `unwrap` fails.
Anyway if I convert the `MyParams.key` to `String`, the code works perfectly.

(serde_json works fine with &str).

Can I try to improve this lib?

Thanks

**Comment by nox** [comment]
Sure, those are `Cow<'de, str>` internally so I don't see why that doesn't currently work.

**Comment by allevo** [comment]
Using `Cow<'de, str>`. Here the link to the playground.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%23%5Bmacro_use%5D%0Aextern%20crate%20serde_derive%3B%0A%0Aextern%20crate%20serde%3B%0Aextern%20crate%20serde_urlencoded%3B%20%2F%2F%200.5.4%3B%0A%0A%23%5Bderive(Deserialize)%5D%0Astruct%20MyParams%3C%27a%3E%20%7B%0A%20%20%20%20key%3A%20%26%27a%20str%0A%7D%0A%0Afn%20main()%20-%3E%20Result%3C()%2C%20Box%3Cstd%3A%3Aerror%3A%3AError%3E%3E%20%7B%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20%22aaa%22)%3B%0A%20%20%20%20let%20r%3A%20MyParams%20%3D%20serde_urlencoded%3A%3Afrom_str(%22key%3Dbb%22).unwrap()%3B%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20r.key)%3B%0A%20%20%20%20Ok(())%0A%7D

Anyway the documentation doesn't say nothing nor tests.
I'll happy to send a PR a test for that case.

**Comment by nox** [comment]
Ok I now understand the problem:

https://github.com/serde-rs/serde/blob/11cc7014b3b2507a19465404599a1999e7c48cce/serde/src/de/value.rs#L612-L648

I misunderstood this impl, and didn't notice that the impl isn't for `CowStrDeserializer<'de, E>`.

**Comment by nox** [comment]
I'll release 0.5.5 as soon as #54 lands.

**Comment by nox** [comment]
Done! Thanks for the bug report.

**Comment by allevo** [comment]
Awesome! Many thanks
