### ISSUE TITLE
Reconsider depending on URL

### ISSUE THREAD

**Issue by gahag** [nox/serde_urlencoded#72]
The URL crate is a dependency of this crate, and it has its own dependencies which are unrelated to this crate, from a quick look. Maybe we should consider moving the actually required code to this crate, and drop the dependency?

**Comment by nox** [comment]
Wrong repository for this issue, please go file one about splitting off the form-urlencoded stuff from the url crate.

**Comment by nox** [comment]
The URL crate is a crate from the Servo project. I work full-time on Servo. We have already thought about splitting the form-urlencoded stuff from it but we don't have time to do that and it's not a priority for us to do so at all at the current comment.

I'm not sure why you think this is the correct repository: I will *never* merge anything that duplicates here the form-urlencoded stuff from the URL crate.

I'm closing this issue.
