### ISSUE TITLE
Arrays support

### ISSUE THREAD

**Issue by elpiel** [nox/serde_urlencoded#75]
## Proposal

It would be nice to have support for arrays since `url` crate already supports this.

## Cases

Both cases will result in:
```rust
[
    ("key", "one"),
    ("key", "two"),
]
```

- `key=one&key=two`
- `key[]=one&key[]=two`

## Examples

```rust
use url; // 2.1.1

fn main() {
    let query = "key=one&key=two";
    let parsed = url::form_urlencoded::parse(query.as_bytes());
    
    let values = parsed.collect::<Vec<_>>();
    dbg!(values);
}
```

```rust
use url; // 2.1.1

fn main() {
    let query = "key[]=one&key[]=two";
    let parsed = url::form_urlencoded::parse(query.as_bytes());
    
    let values = parsed.collect::<Vec<_>>();
    dbg!(values);
}
```

**Comment by nox** [comment]
https://github.com/nox/serde_urlencoded/issues/52

**Comment by nox** [comment]
Note that URLs don't actually support that, the behaviour you describe is not standardised anywhere.

**Comment by elpiel** [comment]
Thanks for taking time to answer
