### ISSUE TITLE
Clarification request: What kind of structs can be deserialized to by this crate?

### ISSUE THREAD

**Issue by jcaesar** [nox/serde_urlencoded#76]
I stumbled upon the same problem as #52, I wanted to deserialize a struct with a `Vec` in it. I found it somewhat surprising that this is not possible, since the compiler accepted my code with a `Vec` in a struct, and wish I had learned earlier that this is a design decision:

> This is a crate for deserializing from query strings as specified by the URL Standard, nothing more, nothing less.

On deserializing query strings, [whatwg](https://url.spec.whatwg.org/#urlencoded-parsing) says "Let `output` be [a] list of name-value tuples where both name and value hold a string." Clearly, rust structs are not lists of tuples.

So what kind of structs can be serialized to?

**Comment by maxv-rust** [comment]
As I understand, only "flat" structs can be [de]serialized. 

So if you struct contain other structs as a fields then it'll be broken.

**Comment by nox** [comment]
Rust structs are list of tuples if you see them as maps from field names to values. As Max said, vectors aren't supported, by design. Use `serde_qs` if you need more.

**Comment by jcaesar** [comment]
Lists of tuples can contain duplicates. Rust structs can't.

Is that really the only difference?
