### ISSUE TITLE
Support sequence-like values in a key-value map

### ISSUE THREAD

**Issue by rubdos** [nox/serde_urlencoded#85]
Consider

```rust
#[derive(Serialize)]
struct Foo {
    field: Vec<String>,
}
```

or

```rust
let foo = [
    "key", vec!["hello", "world"],
]
```

or the `HashMap`-equivalent of the above. These all currently throw "unsupported value" errors. It would be extremely nice to have this supported, and serialized into `key[0]=hello&key[1]=world`.

**Comment by nox** [comment]
Your foo example does not type check, but apart from that such use cases are explicitly out of scope, sorry.

**Comment by nox** [comment]
You may want to use `serde_qs` rather than that crate btw.

**Comment by rubdos** [comment]
> Your foo example does not type check, but apart from that such use cases are explicitly out of scope, sorry.

Woops, forgot to make that an array of tuples, sorry.

> You may want to use `serde_qs` rather than that crate btw.

Thanks for the reference.  Searching for `serde_qs` on the bugtracker of `reqwest` got me https://github.com/nox/serde_urlencoded/issues/46 (so this is a duplicate, sorry again) via https://github.com/seanmonstar/reqwest/issues/274. Thanks!
