### ISSUE TITLE
[DISC] Percent decoding

### ISSUE THREAD

**Issue by erwanvivien** [nox/serde_urlencoded#98]
Hello everyone,

Could we have a feature where `from_str` returns values with no parsing ?

```rust
use std::collections::HashMap;
use serde_urlencoded::from_str; // 0.7.1

let query_string = "id=6%206&abc=123&def=2%252";
let query_string = query_string.replace("%", "%25");

let map = from_str::<HashMap<String, String>>(&query_string).unwrap();

println!("{:?}", map);
```
Which yield
```json
{"id": "6%206", "def": "2%252", "abc": "123"}
```

I'm using the above code for now to escape '%' character

Sorry if issue isn't the best suited place.

Thanks

Edit: added output

**Comment by nox** [comment]
You probably want to file an issue at https://github.com/servo/rust-url/ and use the `percent_encoding` crate directly.

**Comment by erwanvivien** [comment]
Hello @ckcr4lyf,

I'm still, to this day, using the said "hack"...
I do not understand @nox answer, `serde_urlencode` doesn't use https://github.com/servo/rust-url/ ?

Why is there no function to decode only the keys, not the values ?

`id=6%206&abc=123&def=2%252` yieding `{"id": "6%206", "def": "2%252", "abc": "123"}` as mentionned before.

Thanks

**Comment by ckcr4lyf** [comment]
I am not too sure myself, I wasn't really able to read the source that well... I will try and figure out if the % decoding is an issue at this library's usage of rust-url or it comes due to a higher level issue of auto decoding in rust-url

**Comment by ckcr4lyf** [comment]
@erwanvivien  seems it is a design choice by the parent library to not support invalid UTF-8, as is mentioned in this spec which they follow - https://url.spec.whatwg.org/#urlencoded-parsing

Guess no choice except the hack, thanks for sharing it!
